---
title: ownersup.com
timezone: UTC
version: 3.0.3
email: hello@ownersup.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
'
baseurl: ''
url: http://ownersup.com
twitter_username: ownersup
incremental: true
markdown: kramdown

sass:
    #style: compressed
    sass_dir: _scss

gems:
  - jekyll-sitemap
  - jekyll-autoprefixer
  - jekyll-redirect-from
